#output: Publishes geometry_msgs/msg/TwistStamped to cmd_vel topic
joy_teleop:
  ros__parameters:
    move:
      type: topic
      interface_type: geometry_msgs/msg/TwistStamped #output message type is TwistStamped
      topic_name: bumperbot_controller/cmd_vel #this is the published topic
      deadman_buttons: [5] #button which allows moving the robot
      axis_mappings:
        twist-linear-x:
          axis: 1 #moving to the x axis the robot with the joystick
          scale: 1.0
          offset: 0.0
        twist-angular-z:
          axis: 3
          scale: 8.0
          offset: 0.0